server:
  port: 9998
spring:
  redis:
    host:
    port:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:
    username:
    password:
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml